package goib

var multitieredCollectionJson = `
{
  "type" : "COLLECTION",
  "hash" : "v4ba39z",
  "content_id" : 14277682,
  "content_name" : "Dayside Media Window Collection",
  "navigation_context" : [ "WESH Home" ],
  "analytics_category" : "home",
  "advertising_category" : "homepage",
  "title" : null,
  "valid_from" : 2700000,
  "valid_to" : 4105144800,
  "editorial_comment" : null,
  "period" : "Mon-Fri@0545-2230",
  "keywords" : "",
  "url" : "http://www.wesh.com/14277682",
  "canonical_url" : "http://www.wesh.com/-/11788876/14277682/-/9jx95s/-/index.html",
  "teaser_title" : "",
  "teaser_text" : null,
  "teaser_image" : null,
  "media" : [ ],
  "author_objects" : [ ],
  "author" : "",
  "categories" : [ ],
  "creation_date" : 1338315662,
  "copyright_objects" : [ ],
  "copyright" : "",
  "publication_date" : 1415642175,
  "struct" : [ {
  } ],
  "collection_name" : "Dayside Media Window Collection",
  "total_count" : 4,
  "start_index" : 0,
  "items" : [ {
    "type" : "COLLECTION",
    "hash" : "2oio2j",
    "content_id" : 11787596,
    "content_name" : "TOP STORY - Dayside Collection (8 Items)",
    "navigation_context" : [ "WESH Home" ],
    "analytics_category" : "home",
    "advertising_category" : "homepage",
    "title" : null,
    "valid_from" : 2700000,
    "valid_to" : 4105144800,
    "editorial_comment" : null,
    "period" : "",
    "keywords" : "",
    "url" : "http://www.wesh.com/11787596",
    "canonical_url" : "http://www.wesh.com/-/11788876/11787596/-/13dawepz/-/index.html",
    "teaser_title" : "",
    "teaser_text" : null,
    "teaser_image" : null,
    "media" : [ ],
    "author_objects" : [ ],
    "author" : "",
    "categories" : [ ],
    "creation_date" : 1327005100,
    "copyright_objects" : [ ],
    "copyright" : "",
    "publication_date" : 1415837293,
    "struct" : [ {
    } ],
    "collection_name" : "TOP STORY - Dayside Collection (8 Items)",
    "total_count" : 8,
    "start_index" : 0,
    "items" : [ {
      "type" : "ARTICLE",
      "hash" : "6xxykl",
      "content_id" : 29686896,
      "publication_date" : 1415837264,
      "teaser_title" : "Police: Child grazed by bullet in DeLand",
      "teaser_text" : "<p>A child is grazed by a bullet Wednesday night in DeLand, police say.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29686976/highRes/1/-/maxh/225/maxw/300/-/57yneiz/-/B2R4nX-IYAA8deF-jpg.jpg"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xeeky",
      "content_id" : 29679342,
      "publication_date" : 1415825301,
      "teaser_title" : "Suicide victim identified as suspect in parents' deaths",
      "teaser_text" : "<p>A man who committed suicide inside a car during a traffic stop in Memphis has been identified as 30-year-old Sean Petrozzino, a suspect in the killings of his parents.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29551334/highRes/1/-/maxh/225/maxw/300/-/cvp5mjz/-/Petrozzino--Sean-png.png"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xv2d3",
      "content_id" : 29682202,
      "publication_date" : 1415831276,
      "teaser_title" : "SeaWorld experiences drops in attendance, profit, revenue",
      "teaser_text" : "<p>SeaWorld announces a huge dip in third quarter earnings Wednesday.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29684352/medRes/1/-/maxh/225/maxw/300/-/f4j2iv/-/img-SeaWorld-announces-tanking-earnings-for-Orlando-theme-park.jpg"
    }, {
      "type" : "GALLERY",
      "hash" : "tjkkbfz",
      "content_id" : 22671162,
      "publication_date" : 1394084260,
      "teaser_title" : "30 Things to make your life simpler",
      "teaser_text" : "<p>We all want to be more productive. \"Life Hacks\", productivity tricks or shortcut skills, can help.  Review these handy life hacks to see if any can be applied in your daily life.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/22798082/highRes/1/-/maxh/225/maxw/300/-/14skc7gz/-/LIFE-SIMPLER-mw-jpg.jpg"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xv1sr",
      "content_id" : 29682198,
      "publication_date" : 1415831351,
      "teaser_title" : "Vegan mom regains custody of infant after abuse allegations ",
      "teaser_text" : "<p>A Seminole County mother wrapped up in a controversy over medical treatment for her child has regained custody of her baby.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29682916/highRes/2/-/maxh/225/maxw/300/-/d7swacz/-/photo-5-JPG.jpg"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xab51",
      "content_id" : 29673688,
      "publication_date" : 1415825388,
      "teaser_title" : "Students can't do worse than 50% in new grading system",
      "teaser_text" : "<p>There is a new grading system for middle and high school students in Orange County.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29673692/medRes/2/-/maxh/225/maxw/300/-/yutrm3/-/img-New-grading-system.jpg"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xadc1",
      "content_id" : 29673926,
      "publication_date" : 1415832277,
      "teaser_title" : "Police hold Walk & Talk after string of shootings in Sanford",
      "teaser_text" : "<p>Members of the Sanford Police Department walked the streets on Wednesday in an effort to stop a string of violence, which is believed to be a result of rival groups lashing out at one another in the area.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29684886/highRes/1/-/maxh/225/maxw/300/-/15s1h01/-/Cora-Brown-JPG.jpg"
    }, {
      "type" : "ARTICLE",
      "hash" : "6xb18n",
      "content_id" : 29674788,
      "publication_date" : 1415824118,
      "teaser_title" : "Orion spacecraft reaches launch pad in Cape Canaveral",
      "teaser_text" : "<p>NASA's Orion spacecraft reached its launch pad in Cape Canaveral early Wednesday morning.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29674830/medRes/2/-/maxh/225/maxw/300/-/14s6ofu/-/img-Orion-rollout.jpg"
    } ],
    "settings" : [ {
    } ],
    "view_type" : null
  }, {
    "type" : "COLLECTION",
    "hash" : "2ojgex",
    "content_id" : 11788954,
    "content_name" : "TOP STORY - National Dynamic Collection",
    "navigation_context" : [ "WESH Home" ],
    "analytics_category" : "home",
    "advertising_category" : "homepage",
    "title" : null,
    "valid_from" : 2700000,
    "valid_to" : 4105144800,
    "editorial_comment" : null,
    "period" : "",
    "keywords" : "",
    "url" : "http://www.wesh.com/11788954",
    "canonical_url" : "",
    "teaser_title" : "",
    "teaser_text" : null,
    "teaser_image" : null,
    "media" : [ ],
    "author_objects" : [ ],
    "author" : "",
    "categories" : [ ],
    "creation_date" : 1326991382,
    "copyright_objects" : [ ],
    "copyright" : "",
    "publication_date" : 1347035712,
    "struct" : [ {
    } ],
    "collection_name" : "TOP STORY - National Dynamic Collection",
    "total_count" : 1,
    "start_index" : 0,
    "items" : [ {
      "type" : "ARTICLE",
      "hash" : "6xucdv",
      "content_id" : 29681152,
      "publication_date" : 1415835412,
      "teaser_title" : "Fox News reviews Huckabee political activity",
      "teaser_text" : "<p>Fox News and potential presidential candidate Ben Carson went their separate ways last week. Is Fox host and former Arkansas Gov. Mike Huckabee next? </p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/4685130/highRes/2/-/maxh/225/maxw/300/-/axjhqj/-/Mike-Huckabee-waving-jpg.jpg"
    } ],
    "settings" : [ {
    } ],
    "view_type" : null
  }, {
    "type" : "COLLECTION",
    "hash" : "2oioms",
    "content_id" : 11787612,
    "content_name" : "u Local",
    "navigation_context" : [ "WESH Home" ],
    "analytics_category" : "home",
    "advertising_category" : "homepage",
    "title" : null,
    "valid_from" : 2700000,
    "valid_to" : 4105144800,
    "editorial_comment" : null,
    "period" : "",
    "keywords" : "",
    "url" : "http://www.wesh.com/11787612",
    "canonical_url" : "http://www.wesh.com/-/11788876/11787612/-/13davtgz/-/index.html",
    "teaser_title" : "u Local",
    "teaser_text" : null,
    "teaser_image" : null,
    "media" : [ ],
    "author_objects" : [ ],
    "author" : "",
    "categories" : [ ],
    "creation_date" : 1331831228,
    "copyright_objects" : [ ],
    "copyright" : "",
    "publication_date" : 1415131655,
    "struct" : [ {
    } ],
    "collection_name" : "u Local",
    "total_count" : 2,
    "start_index" : 0,
    "items" : [ {
      "type" : "TEASER",
      "hash" : "k1j1d7",
      "content_id" : 17336936,
      "publication_date" : 1352473316,
      "teaser_title" : "Honor your hero this Veterans Day on u local",
      "teaser_text" : "<p>In celebration of Veterans Day, share photos along with stories of the heroes that have made an impact in your life.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/17267384/highRes/22/-/maxh/225/maxw/300/-/jjsmnez/-/Veterans-Day-11-12-Master-Image.jpg",
      "target" : {
        "type" : "ARTICLE",
        "hash" : "k1j1d1",
        "content_id" : 17336930,
        "publication_date" : 1414990800,
        "teaser_title" : "Honor your hero this Veterans Day on u local",
        "teaser_text" : "<p><a href=\"http://www.wesh.com/ulocal/17336928\" target=\"_blank\">Using the App? Upload your photos to using the u local tab on the home screen.</a></p>",
        "teaser_image" : null
      }
    }, {
      "type" : "TEASER",
      "hash" : "klqa32",
      "content_id" : 17451500,
      "publication_date" : 1415130618,
      "teaser_title" : "Get in the Thanksgiving spirit on u local ",
      "teaser_text" : "<p>Celebrate Thanksgiving by showing us what you're thankful for on u local.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/17272638/highRes/25/-/maxh/225/maxw/300/-/l8u99rz/-/Thanksgiving-Master-Image.jpg",
      "target" : {
        "type" : "ARTICLE",
        "hash" : "klqa38",
        "content_id" : 17451506,
        "publication_date" : 1352001600,
        "teaser_title" : "Get in the Thanksgiving spirit on u local ",
        "teaser_text" : "<p>Thanksgiving means different things to many different people, and we want to know what you're thankful for on u local!</p>",
        "teaser_image" : null
      }
    } ],
    "settings" : [ {
    } ],
    "view_type" : null
  }, {
    "type" : "COLLECTION",
    "hash" : "bnlhnz",
    "content_id" : 8629560,
    "content_name" : "TOP STORY - Hearst Clicker",
    "navigation_context" : [ "Hearst Shared Content Parent", "News Clickers" ],
    "analytics_category" : "news",
    "advertising_category" : "homepage",
    "title" : null,
    "valid_from" : 2700000,
    "valid_to" : 4105144800,
    "editorial_comment" : null,
    "period" : "",
    "keywords" : "",
    "url" : "http://www.wesh.com/news/8629560",
    "canonical_url" : "http://prewww.htvshared.com/News-Clickers/-/8761650/8629560/-/6djal1z/-/index.html",
    "teaser_title" : " ",
    "teaser_text" : null,
    "teaser_image" : null,
    "media" : [ ],
    "author_objects" : [ ],
    "author" : "",
    "categories" : [ ],
    "creation_date" : 1328916144,
    "copyright_objects" : [ ],
    "copyright" : "",
    "publication_date" : 1399357593,
    "struct" : [ {
    } ],
    "collection_name" : "TOP STORY - Hearst Clicker",
    "total_count" : 1,
    "start_index" : 0,
    "items" : [ {
      "type" : "GALLERY",
      "hash" : "4rkud5",
      "content_id" : 29283428,
      "publication_date" : 1414009612,
      "teaser_title" : "Most unique jobs in each state",
      "teaser_text" : "<p>Each state has specific jobs that are most unique to that location and people. Find out which job is most unique to your state in this newly released study from CareerBuilder.</p>",
      "teaser_image" : "http://www.wesh.com/image/view/-/29283344/highRes/1/-/maxh/225/maxw/300/-/oxwh3qz/-/uniquejobs-mw-jpg.jpg"
    } ],
    "settings" : [ {
      "teasable.meta.updatedAt.relative" : "true",
      "teasable.meta.updatedAt.onlyRelative" : "true"
    } ],
    "view_type" : null
  } ],
  "settings" : [ {
    "collection.teaser.showTimestamp" : "true",
    "teasable.meta.updatedAt.onlyRelative" : "true",
    "collection.teaser.image.isCaption" : "false",
    "collection.teaser.showMoreText" : "true",
    "collection.teaser.imageOnTop" : "true",
    "collection.teaser.showMediaLink" : "true",
    "collection.teaser.title.trimLength" : "150",
    "teasable.meta.updatedAt.relative" : "true",
    "collection.jQueryTOOLS.autoscroll.breaking" : "false",
    "collection.teaser.image.isCopyright" : "true",
    "collection.teaser.image.scaleToHeight" : "252",
    "collection.jQueryTOOLS.autoscroll.interval" : "8.2",
    "collection.teaser.image.scaleToWidth" : "378",
    "collection.teaser.image.showCopyright" : "true"
  } ],
  "view_type" : "rotating"
}
`
